namespace PicoPDF.OpenType;

public enum NameIDs
{
    CopyrightNotice = 0,
    FontFamilyName = 1,
    FontSubfamilyName = 2,
    UniqueFontIdentifier = 3,
    FullFontName = 4,
    Version = 5,
    PostScriptName = 6,
    Trademark = 7,
    ManufacturerName = 8,
    Designer = 9,
    Description = 10,
    URLOfVendor = 11,
    URLOfDesigner = 12,
    LicenseDescription = 13,
    LicenseInfoURL = 14,
    Reserved = 15,
    TypographicFamilyName = 16,
    TypographicSubfamilyName = 17,
    CompatibleFull = 18,
    SampleText = 19,
    PostScriptCIDFindFontName = 20,
    WWSFamilyName = 21,
    WWSSubfamilyName = 22,
    LightBackgroundPalette = 23,
    DarkBackgroundPalette = 24,
    VariationsPostScriptNamePrefix = 25,
}
